Improve robustness of asset sync
ForgeVTT/fvtt-module-forge-vtt pull request #16
Opened 2023-11-01 20:34 UTC by Eranziel

Closes #14.

This PR includes the following updates:
- Continue asset sync if some folders failed to be created.
- Skip assets in folders which are missing locally.
- Make use of the existing but unused `failedFolders` and `failedAsses` variables.
- Display the list of failed folders and assets in the UI, update the "failed with errors" message.
- Fix a bug which would cause asset sync with a non-root-folder API key to attempt to sync the root folder of the target Assets Library instead of the base folder of the API key.
- Fix a cause of mismatches between local and Forge assets due to un-decoded URLs.

2023-11-01 22:22 UTC, rikmarais requested changes
This looks good 👍 

Just some TODO comments that we can remove now. 

![image](https://github.com/ForgeVTT/fvtt-module-forge-vtt/assets/34374883/3133516d-5c84-4a14-ac33-286ed942e730)

I was unfortunately not able to reproduce the error encountered [here](https://github.com/ForgeVTT/fvtt-module-forge-vtt/issues/14#issuecomment-1782058550) with this implementation, but the error handling added here should handle. I tested with similar paths and they did get caught correctly.

2023-11-02 19:17 UTC, Eranziel commented on assets-sync.js
>                  // @todo maybe predicate this on receiving a "true" from previous methods?
Done

2023-11-02 19:17 UTC, Eranziel commented on assets-sync.js
>      static async fetchLocalEtag(path) {
Done

2023-11-02 19:24 UTC, rikmarais approved these changes

2023-11-02 19:24 UTC, rikmarais commented
LGTM! Thanks for the changes!

2023-11-02 19:24 UTC, merged